### ISSUE TITLE
UI allows selection of incompatible similarity metric & representation models

### ISSUE THREAD

**Issue by GabrielePisciotta** [scify/jedai-ui#1]
Selecting a wrong similarity metric for "Entity Matching" will cause the UI to crash with
`ERROR minlog:186 - The given similarity metric is incompatible with the n-gram graphs representation model!`

**Comment by leots** [comment]
Hi Gabriele, 
Thanks for reporting this. It is in our immediate plans to improve the selection of similarity metric & representation model in order to only allow valid choices to be made.

Leonidas
