### ISSUE TITLE
Maven dependency could not be resolved

### ISSUE THREAD

**Issue by saphyll** [scify/jedai-ui#10]
Hello,
I have encountered following error, when I tried to get Jedai-UI up and running for the first time:
Could not resolve dependencies for project org.scify:jedai-ui:jar:1.3: Could not find artifact org.scify:jedai-core:jar:3.0-SNAPSHOT in oss.sonatype.org-snapshot (http://oss.sonatype.org/content/repositories/snapshots)

I haven't got much experience with Maven, so it's possible that I'm missing something.

--Edit-- 
I replaced the snapshot dependency with plain jedai-core, but there is another dependency throwing an error now:
Could not resolve dependencies for project org.scify:jedai-ui:jar:1.3: Could not transfer artifact com.esotericsoftware.minlog:minlog:jar:1.2-slf4j-jdanbrown-0 from/to premise (http://premise.artifactoryonline.com/premise/public): Transfer failed for http://premise.artifactoryonline.com/premise/public/com/esotericsoftware/minlog/minlog/1.2-slf4j-jdanbrown-0/minlog-1.2-slf4j-jdanbrown-0.jar 308 Permanent Redirect

**Comment by leots** [comment]
Hi @saphyll,

We updated the version of jedai-core in the dependencies. Now it should work. If not, you can reopen the issue.

Thanks for reporting this!

**Comment by digamber1729** [comment]
Hi,
I am facing the same issue again, unable to build the jed-UI, Can you please verify and update the maven dependencies.

**Comment by AlexJoom** [comment]
Hi @digamber1729 , can you please git pull and try again?  It should work now
