### ISSUE TITLE
Unable to build jedai-ui as code has changed since jedai-core 3.0

### ISSUE THREAD

**Issue by lwj5** [scify/jedai-ui#8]
Hi,

`mvn clean package` does not work anymore as the latest jedai-ui code is not compatible with jedai-core 3.0, thus it cannot be built and packaged.

Could you help to:
- push jedai-core 3.1 to maven central
- switch the pom.xml to use jedai-core 3.1
- create a new release for jedai-ui on https://github.com/scify/jedai-ui/releases or tag the commit so that while you work on master branch, users are still able to build from an older stable version using the tags

Additionally, if you could release the jar with dependencies in the releases section that would be the best.

Thank you

**Comment by gpapadis** [comment]
Dear Ween,

we have updated the jedai-core in maven (without changing the version though). 

Thank you very much for your valuable help in improving JedAI.

Kind regards,
George

**Comment by lwj5** [comment]
Dear George,

Thanks for the reply. Unfortunately all release to ossrh-release (maven-release) are immutable and cannot be overwritten.

I have created a PR here https://github.com/scify/JedAIToolkit/pull/31 so that you can push to ossrh-snapshot instead which is mutable and can be overwritten. It also allows you to use this snapshot in other projects like jedai-ui during development.

Snapshots are meant for development and will not be listed on the release catalog.

**Comment by lwj5** [comment]
Just for your info, OSSRH is currently down so you wont be able to push just yet.

You can see the status at https://status.maven.org/
